#!/bin/bash
#
# Common functions for all tests to use
#

_run_duperemove()
{
    if [ ! -x $DUPEREMOVE ]; then
	echo "TEST FAILURE: No duperemove executable at $DUPEREMOVE"
	exit 1;
    fi

    $DUPEREMOVE $*
    _ret=$?
    if [ $_ret -ne 0 ]; then
	echo "TEST FAILURE: Error code is $_ret"
	exit 1
    fi
}

_run_dd()
{
    dd status=none $@
    _ret=$?
    if [ $_ret -ne 0 ]; then
	echo "dd failure: Error code is $_ret"
	exit 1
    fi
}

_run_mkzeros()
{
    $MKZEROS -q $@
    _ret=$?
    if [ $_ret -ne 0 ]; then
	echo "dd failure: Error code is $_ret"
	exit 1
    fi
}
